config/routes.rb
Rails.application.routes.draw do
  root to: "homes#top"
  devise_for :users
  # For details  the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :books
  resources :users
  get 'home/about' => "homes#about"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  has_one_attached :image
  belongs_to :user
  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }

  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/default-image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :profile_image
  has_many :books, dependent: :destroy
  validates :name, length: { in: 2..20 }, uniqueness: true
  validates :introduction, length: { maximum: 50 }

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'no_image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(resource)
  end


  def after_sign_out_path_for(resource)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end



end

app/controllers/books_controller.rb
class BooksController < ApplicationController

   before_action :is_matching_login_user, only: [:edit, :update]

  def new
    @book = Book.new
  end

  def create
    @books = Book.all
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book)
      flash[:notice] = "You have created book successfully."
    else
      render :index
    end
  end

  def index
    @books = Book.all
    @book = Book.new
  end

  def show
    @book = Book.find(params[:id])
    @books = Book.new
    @user = @book.user
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  def edit
    @book = Book.find(params[:id])
    @user = @book.user
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book.id)
      flash[:notice] = "You have updated book successfully."
    else
      render :edit
    end
  end

   private

  def book_params
    params.require(:book).permit(:title, :body)
  end

  def is_matching_login_user
    book = Book.find(params[:id])
    unless book.user_id == current_user.id
      redirect_to books_path
    end
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
   
  def about
    
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def index
    @users = User.all
    @book = Book.new
  end

  def edit
    is_matching_login_user
    @user = User.find(params[:id])
  end

  def update
    is_matching_login_user
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path
      flash[:notice] = "You have updated user successfully."
    else
      render :edit
    end
  end

  def destroy
    reset_session
    redirect_to root_path, notice: 'Signed out successfully.'
  end

     private

  def user_params
    params.require(:user).permit(:name, :introduction,:image)
  end

  def is_matching_login_user
    user = User.find(params[:id])
    unless user.id == current_user.id
      redirect_to user_path(current_user.id)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_new.html.erb
<h2>New book</h2>
<%= form_with model: books do |f| %>
  <h4>Title</h4>
  <%= f.text_field :title, class: "book[title]" %>
  <h4>Opinion</h4>
  <%= f.text_area :body, class: "book[body]" %><br>
  <%= f.submit 'Create Book' %>
<% end %>

app/views/books/edit.html.erb
<% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this obj from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
<div class="col-sm-11 col-md-8 mx-auto">
<h1>Editing Book</h1>
<%= form_with model: @book do |f| %>
  <label for="inputTitle">Title</label><br>
  <%= f.text_field :title, autofocus: true, id:"inputTitle" %><br>
  <label for="inputBody">Opinion</label><br>
  <%= f.text_area :body,  autofocus: true, id:"inputBody" %><br>
  <%= f.submit "Update Book" %><br>
  <%= link_to "Show",book_path(@book) %>
  <%= link_to "Back","/books" %>
<% end %>
</div>

app/views/books/index.html.erb
<% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this obj from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<div class="col-md-3">
<%= render 'users/info', user: current_user %>
<%= render 'new', books: @book %>
</div>
<div class="col-md-8 offset-md-1">
  <h2>Books</h2>
<table class="table table-hover table-inverse">
<tr>
  <th></th>
  <th>Title</th>
  <th>Opinion</th>
</tr>


<% @books.each do |book| %>
  <tr>
    <td><%= link_to user_path(book.user.id) do %>
      <%= image_tag book.user.get_profile_image(100,100) %>
      <% end %></td>
    <td>
      <%= link_to book_path(book.id) do %>
        <%= book.title %></td>
      <% end %>
    <td><%= book.body %></td>
  </tr>
<% end %>
</table>
</div>

app/views/books/show.html.erb
<div class="col-md-3">
<%= render 'users/info', user: @user %>
<%= render 'new', books: @books %>
</div>
<div class="col-md-8 offset-md-1">
  <h2>Book detail</h2>
  <table class="table">
    <tr>
    <td><%= link_to  user_path do %><%= image_tag @book.user.get_profile_image(100,100) %><br><%= @book.user.name %><% end %></td>
    <td><%= link_to @book.title, book_path %></td>
    <td><%= @book.body %></td>
    <% if @book.user == current_user %>
      <td><%= link_to "Edit", edit_book_path(@book) %></td>
      <td><%= link_to "Destroy", book_path(@book), method: :delete, "data-confirm" => "本当に削除しますか？" %></td>
    <% end %>
    </tr>
    </table>
</div>

app/views/homes/about.html.erb
<div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
  <h1>Welcome to <i class="fa-solid fa-book"></i>Bookers!</h1>
</div>

app/views/homes/top.html.erb
<div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
  <h1>welcome to <i class="fa-solid fa-book"></i>Bookers!</h1>
  <p>In <i class="fa-solid fa-book"></i>Bookers,</p>
  <p>you can shareand exchange your opinions , inpressions , and emotions</p>
  <p>about various books!</p>
  <div class="btn-wrapper col-10 mx-auto">
    <div class="btn btn-info btn-sm btn-block mb-3">
      <%= link_to "Log in", new_user_session_path %><br>
    </div>
    <div class="btn btn-success btn-sm btn-block">
      <%= link_to "Sign up", new_user_registration_path %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/fa8a8d0d64.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">

      <header class="bg-dark">
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
         <div class="container">
          <h4>
            <%= link_to root_path do %>
              <span>Bookers</span>
            <% end %>
          </h4>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>
                <li class="nav-item"><%= link_to current_user do %><i class="fa-solid fa-house"></i>Homes<% end %></li>
                <li class="nav-item"><%= link_to users_path do %><i class="fa-solid fa-users"></i>Users<% end %></li>
                <li class="nav-item"><%= link_to books_path do %><i class="fa-solid fa-book-open"></i>Books<% end %></li>
                <li class="nav-item"><%= link_to destroy_user_session_path, method: :delete do %><i class="fa-solid fa-right-from-bracket"></i>Log out<% end %></li>
              <% else %>
                <li class="nav-item"><%= link_to "../" do %><i class="fa-solid fa-house"></i>Home<% end %></li>
                <li class="nav-item"><%= link_to "/home/about" do%><i class="fa-solid fa-link"></i>About<% end %></li>
                <li class="nav-item"><%= link_to new_user_registration_path do %><i class="fa-solid fa-user-plus"></i>Sign up<% end %></li>
                <li class="nav-item"><%= link_to new_user_session_path do %><i class="fa-solid fa-right-to-bracket"></i>Log in<% end %></li>
              <% end %>
            </ul>
          </div>
          </div>
        </nav>
      </header>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <main class="mb-auto">
      <div class="container">
      <div class="row">
        <%= yield %>
      </div>
      </div>
    </main>

    <footer class="pt-5 pb-4">
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">CopyRight Infratop.inc</div>
        </div>
      </div>
    </footer>

  </body>
</html>

app/views/users/_info.html.erb
<h2>User Info</h2>
<%= image_tag user.get_profile_image(100,100) %>
<table class="table">
  <tr>
    <th>name</th>
    <th><%= user.name %></th>
  </tr>
  <tr>
    <th>introduction</th>
    <th><%= user.introduction %></th>
  </tr>
</table>

    <%= link_to  edit_user_path(user) do %>
    <i class="fa-solid fa-user-gear"></i>
    <% end %>

app/views/users/edit.html.erb
<% if @user.errors.any? %>
  <%= @user.errors.count %>errors prohibited this obj from being saved:
  <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
<div class="col-sm-12 col-md-8 col-lg-5 mx-auto">
  <h2>User info</h2>
  <%= form_with model: @user do |f| %>
    <label for="inputName">Name</label><br>
    <%= f.text_field :name, autofocus: true, id:"inputName" %><br>
    <label for="inputImage">Image</label><br>
    <%= f.file_field :profile_image, placeholder: "プロフィール画像", accept: "image/*" %><br>
    <label for="inputIntroduction">Introduction</label><br>
    <%= f.text_area :introduction, autofocus: true, id:"inputIntroduction" %><br>
    <%= f.submit "Update User" %>
  <% end %>
</div>

app/views/users/index.html.erb
<div class="col-md-3">
  <%= render 'users/info', user: current_user %>
  <%= render 'books/new', books: @book %>
</div>
<div class="col-md-8 offset-md-1">
  <h2>Users</h2>
  <table class="table table-hover table-inverse">
    <tr>
  <th>image</th>
  <th>name</th>
  <th></th>
</tr>
    <% @users.each do |user| %>
      <tr>
        <td><%= image_tag user.get_profile_image(100,100) %></td>
        <td><%= user.name %></td>
        <td><%= link_to "Show", user_path(user.id) %></td>
      </tr>
    <% end %>
  </table>
</div>

app/views/users/show.html.erb
<div class="col-md-3">
  <%= render 'users/info', user: @user %>
  <%= render 'books/new', books: @book %>
</div>
<div class="col-md-8 offset-md-1">
  <h2>Books</h2>
  <table class="table">
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
    </tr>
    <% @user.books.each do |book| %>
    <tr>
      <td><%= link_to user_path(book.user.id) do %>
      <%= image_tag book.user.get_profile_image(100,100) %>
      <% end %></td>
      <td><%= link_to book_path(book.id) do %>
        <%= book.title %>
      <% end %></td>
      <td><%= book.body %></td>
    </tr>
    <% end %>
  </table>
</div>